### ISSUE TITLE
Can't run whit this docker-compose.yml

### ISSUE THREAD

**Issue by qwm** [appleboy/nginx-image-resizer#11]
2018/09/18 08:27:27 [emerg] 16#16: invalid keys zone size "keys_zone=cache_zone:" in /etc/nginx/conf.d/default.conf:1
nginx: [emerg] invalid keys zone size "keys_zone=cache_zone:" in /etc/nginx/conf.d/default.conf:1

**Comment by appleboy** [comment]
I will take it.

**Comment by appleboy** [comment]
Try the latest tag `v1.0.1` or default image.
